cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

before_script:
  - export PATH=$PATH:/home/gitlab-runner/.nvm/versions/node/v11.11.0/bin/
  #- export URL=http://translatetest.mdlib.vn/
  - npm i
  - NODE_OPTIONS=--max-old-space-size=4096

stages:
  - deploy

deployN4:
  stage: deploy
  only:
    refs:
      - master
      - cicd
  script:
    #- sed -i "s/HTTP/http/g" package.json
    #- sed -i "s/DOMAIN/translate2.mdlib.vn/g" package.json
    #- sed -i "s/WS/ws/g" .env.production.local
    #- sed -i "s/HTTP/http/g" .env.production.local
    #- sed -i "s/DOMAIN/translate2.mdlib.vn/g" .env.production.local
    #- cat package.json | grep homepage
    - CI="" npm run build
    - rsync -a -e "ssh -p 1210" ./build/ deploy@192.168.88.104:/var/www/erp_beta/lunch4 --delete
